version: '3.7'

services:
  business-central:
    image: quay.io/kiegroup/business-central-workbench:7.73.0.Final
    container_name: business-central
    ports:
      - "3366:8080"
    volumes:
      - ./users.properties:/opt/jboss/wildfly/standalone/configuration/application-users.properties
      - ./roles.properties:/opt/jboss/wildfly/standalone/configuration/application-roles.properties
    networks:
      - drools-net

  kieserver:
    image: quay.io/kiegroup/kie-server:7.73.0.Final
    container_name: kieserver
    ports:
      - "3367:8080"
    environment:
      - KIE_SERVER_CONTROLLER=http://business-central:8080/business-central/rest/controller
      - KIE_SERVER_CONTROLLER_USER=admin
      - KIE_SERVER_CONTROLLER_PWD=admin123
      - KIE_MAVEN_REPO=http://business-central:8080/business-central/maven2
    volumes:
      - ./users.properties:/opt/jboss/wildfly/standalone/configuration/application-users.properties
      - ./roles.properties:/opt/jboss/wildfly/standalone/configuration/application-roles.properties
    depends_on:
      - business-central
    networks:
      - drools-net

networks:
  drools-net:
    driver: bridge
