version: "3.8"

services:
  postgres-drools:
    image: postgres:14
    restart: always
    container_name: drools-db
    environment:
      POSTGRES_DB: drools
      POSTGRES_USER: drools
      POSTGRES_PASSWORD: droolspw
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

  drools-workbench:
    image: jboss/business-central-workbench-showcase:7.61.0.Final
    container_name: drools-workbench
    ports:
      - "3366:8080"       # accéder à Business Central via http://localhost:3366/business-central
    environment:
      - DB_HOST=drools-db
      - DB_PORT=5432
      - DB_SCHEMA=drools
      - DB_USER=drools
      - DB_PWD=droolspw
      - KIE_SERVER_CONTROLLER=http://drools-workbench:8080/kie-wb/rest/controller
    depends_on:
      - postgres-drools
    networks:
      - spring-net

  kie-server:
    image: jboss/kie-server-showcase:7.61.0.Final
    container_name: kie-server
    ports:
      - "3367:8080"       # accès au KIE Server REST sur http://localhost:3367
    environment:
      - KIE_SERVER_CONTROLLER=http://drools-workbench:8080/kie-wb/rest/controller
      - KIE_SERVER_USER=kieuser
      - KIE_SERVER_PWD=kiepwd
    depends_on:
      - drools-workbench
    networks:
      - spring-net

volumes:
  pgdata:

networks:
  spring-net:
    driver: bridge
