version: '3.8'

services:
  customer-service:
    build: ./customer-service
    container_name: customer-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8081"
    networks:
      - spring-net

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8082:8082"
    networks:
      - spring-net
networks:
  spring-net: