version: '3.8'

services:
  config-server:
    container_name: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring-net

  customer-db:
    image: postgres:15
    restart: always
    container_name: customer-db
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - spring-net

  order-db:
    image: postgres:15
    restart: always
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - spring-net

  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - spring-net

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      - customer-db
      - config-server
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8081"
    networks:
      - spring-net

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - order-db
      - config-server
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8082:8082"
    networks:
      - spring-net
networks:
  spring-net: